#!/bin/php
<?php
/**
 * Provide a simple way to invoke our plugins from a call to Hestia's API (bin directory).
 */

// Check for root user
$user = posix_getpwuid(posix_getuid())['name'];
if ($user !== 'root') {
  echo "Only root user can invoke this script.\n";
  exit(1);
} 

require_once( '/etc/hestiacp/hooks/pluginable.php' );
global $hcpp;

// Pass along any arguments
array_shift( $argv );
$hcpp->do_action( 'hcpp_invoke_plugin', $argv );
