#!/bin/php
<?php
/**
 * Provide a simple way to invoke our plugins from a call to Hestia's API (bin directory).
 */
require_once( '/usr/local/hestia/web/pluginable.php' );
global $hcpp;

// Pass along any arguments
array_shift( $argv );
$hcpp->do_action( 'hcpp_invoke_plugin', $argv );